Algoritmo "semnome"
// Disciplina   : [Lógica de Programação]
// Professor   : Arthur Antunes Ferreira
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/11/2020
Var
   // Seção de Declarações das variáveis
   num : inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   num := 1
   enquanto num > 0 faca
      escreva("Digite um número positivo: ")
      leia(num)
   fimenquanto

Fimalgoritmo